# Rhythm mapping
rhythm_mapping = {
    0: 'blank',
    1: 'barline_light',
    2: 'barline_light-light',
    3: 'beam8thDown',
    4: 'beam8thUp',
    5: 'beamDownEnd',
    6: 'beamDownStart',
    7: 'beamUpEnd',
    8: 'beamUpStart',
    9: 'C-Clef',
    10: 'dot',
    11: 'eighthRest',
    12: 'endSlur',
    13: 'flag16thDown',
    14: 'flag8thDown',
    15: 'flag8thUp',
    16: 'flat',
    17: 'halfRest',
    18: 'mmrSymbol_1',
    19: 'mmrSymbol_2',
    20: 'mmrSymbol_3',
    21: 'natural',
    22: 'noteheadBlack',
    23: 'noteheadHalf',
    24: 'noteheadWhole',
    25: 'quarterRest',
    26: 'sharp',
    27: 'startSlur',
    28: 'steamQuarterHalfDown',
    29: 'steamQuarterHalfUp',
    30: 'timeSig_common',
    31: '32thRest',
    32: 'epsilon'
}

# Hard-coded modified pitch mapping
pitch_mapping = {
    0: 'blank',
    1: 'noNote',
    2: 'L1',
    3: 'L2',
    4: 'L3',
    5: 'L4',
    6: 'L5',
    7: 'L6',
    8: 'S1',
    9: 'S2',
    10: 'S3',
    11: 'S4',
    12: 'S5',
    13: 'S6',
    14: 'epsilon'
}

# inverse mappings
inverse_rhythm_mapping = {
    'blank': 0,
    'barline_light': 1,
    'barline_light-light': 2,
    'beam8thDown': 3,
    'beam8thUp': 4,
    'beamDownEnd': 5,
    'beamDownStart': 6,
    'beamUpEnd': 7,
    'beamUpStart': 8,
    'C-Clef': 9,
    'dot': 10,
    'eighthRest': 11,
    'endSlur': 12,
    'flag16thDown': 13,
    'flag8thDown': 14,
    'flag8thUp': 15,
    'flat': 16,
    'halfRest': 17,
    'mmrSymbol_1': 18,
    'mmrSymbol_2': 19,
    'mmrSymbol_3': 20,
    'natural': 21,
    'noteheadBlack': 22,
    'noteheadHalf': 23,
    'noteheadWhole': 24,
    'quarterRest': 25,
    'sharp': 26,
    'startSlur': 27,
    'steamQuarterHalfDown': 28,
    'steamQuarterHalfUp': 29,
    'timeSig_common': 30,
    '32thRest': 31,
    'epsilon': 32
}

inverse_pitch_mapping = {
    'blank': 0,
    'noNote': 1,
    'L1': 2,
    'L2': 3,
    'L3': 4,
    'L4': 5,
    'L5': 6,
    'L6': 7,
    'S1': 8,
    'S2': 9,
    'S3': 10,
    'S4': 11,
    'S5': 12,
    'S6': 13,
    'epsilon': 14
}
